# Generated by Django 5.1.1 on 2024-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_city_alter_profile_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("restaurant_owner", "Restaurant Owner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("restaurant_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "restaurant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upload_image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
