# Generated by Django 5.1.1 on 2024-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                ],
                default="available",
                max_length=15,
            ),
        ),
    ]
